from app.models.student_evaluations.evaluation_questions import EvaluationQuestions
from app.models.student_evaluations.evaluation_details import EvaluationDetails
from app.models.student_evaluations.evaluations import Evaluations
from app.models.student_evaluations.evaluation_details_tmp import EvaluationDetailsTmp
from app.models.student_evaluations.evaluations_tmp import EvaluationsTmp