"""new primary key for evaluations_details

Revision ID: 07b07733c241
Revises: 9240bd814696
Create Date: 2023-12-02 15:18:38.335283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b07733c241'
down_revision = '9240bd814696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_details', schema=None) as batch_op:
        batch_op.drop_column('course')

    # ### end Alembic commands ###
