"""updated model for publications

Revision ID: 4d71c164700f
Revises: 533145b1977c
Create Date: 2024-02-10 16:41:12.179890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d71c164700f'
down_revision = '533145b1977c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sa.String(length=5000), nullable=False))
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('authors')

    # ### end Alembic commands ###
