"""instructor rating

Revision ID: 9240bd814696
Revises: bcd5458db569
Create Date: 2023-12-02 15:07:41.706363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9240bd814696'
down_revision = 'bcd5458db569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_rating_mean', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('instructor_rating_mean', sa.Float(), nullable=False))
        batch_op.drop_column('overall_rating_mean')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_rating_mean', sa.FLOAT(), nullable=False))
        batch_op.drop_column('instructor_rating_mean')
        batch_op.drop_column('course_rating_mean')

    # ### end Alembic commands ###
