"""remove id column

Revision ID: a5816a117a3d
Revises: c91f22c2ddc4
Create Date: 2023-11-18 19:15:54.724409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5816a117a3d'
down_revision = 'c91f22c2ddc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_id', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=True))
        batch_op.create_unique_constraint('uq_user_id', ['id'])

    # ### end Alembic commands ###
