"""id column for user2

Revision ID: b54df88aca1e
Revises: ebfb3cc98540
Create Date: 2023-11-18 19:00:56.473144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54df88aca1e'
down_revision = 'ebfb3cc98540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id2', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_id2'), ['id2'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_id2'), type_='unique')
        batch_op.drop_column('id2')

    # ### end Alembic commands ###
