"""Added database models developed by Mitchell

Revision ID: b74792695b29
Revises: a5816a117a3d
Create Date: 2023-11-30 17:44:14.758964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74792695b29'
down_revision = 'a5816a117a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.String(length=100), nullable=False),
    sa.Column('instructor_type', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('participants_count', sa.Integer(), nullable=False),
    sa.Column('number_of_returns', sa.Integer(), nullable=False),
    sa.Column('stated_objective_mean', sa.Float(), nullable=False),
    sa.Column('stated_objective_std_deviation', sa.Float(), nullable=False),
    sa.Column('stated_objective_median', sa.Float(), nullable=False),
    sa.Column('stated_objective_returns', sa.Float(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email', 'year', 'semester', name=op.f('pk_evaluations'))
    )
    op.create_table('expenditures',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('reporting_department', sa.String(length=100), nullable=False),
    sa.Column('pi_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email', 'year', name=op.f('pk_expenditures'))
    )
    op.create_table('grants',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email', 'title', name=op.f('pk_grants'))
    )
    op.create_table('publications',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('publication_year', sa.String(length=100), nullable=False),
    sa.Column('isbn', sa.String(length=100), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email', 'title', name=op.f('pk_publications'))
    )
    op.drop_table('course_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('crn', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_course_data')
    )
    op.drop_table('publications')
    op.drop_table('grants')
    op.drop_table('expenditures')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
