"""rem

Revision ID: c91f22c2ddc4
Revises: b54df88aca1e
Create Date: 2023-11-18 19:01:38.688787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91f22c2ddc4'
down_revision = 'b54df88aca1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_id2', type_='unique')
        batch_op.drop_column('id2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id2', sa.INTEGER(), nullable=True))
        batch_op.create_unique_constraint('uq_user_id2', ['id2'])

    # ### end Alembic commands ###
