"""changed models for student evaluations to include all questions from the survey

Revision ID: dbe5a5b4f78a
Revises: 06a4e316efb8
Create Date: 2023-12-02 14:55:32.254784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe5a5b4f78a'
down_revision = '06a4e316efb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_details',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.String(length=100), nullable=False),
    sa.Column('questionId', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('returns', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('email', 'year', 'semester', 'questionId', name=op.f('pk_evaluation_details'))
    )
    op.create_table('evaluation_questions',
    sa.Column('questionId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questionText', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('questionId', name=op.f('pk_evaluation_questions'))
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_rating_mean', sa.Float(), nullable=False))
        batch_op.drop_column('stated_objective_std_deviation')
        batch_op.drop_column('stated_objective_mean')
        batch_op.drop_column('stated_objective_returns')
        batch_op.drop_column('stated_objective_median')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stated_objective_median', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('stated_objective_returns', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('stated_objective_mean', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('stated_objective_std_deviation', sa.FLOAT(), nullable=False))
        batch_op.drop_column('overall_rating_mean')

    op.drop_table('evaluation_questions')
    op.drop_table('evaluation_details')
    # ### end Alembic commands ###
